### ISSUE TITLE
Closure can't be serialized

### ISSUE THREAD

**Issue by thib3113** [sebastianbergmann/global-state#13]
In my current project, I've get the error "Closure can't be serialized", without any informations (lines, or files) .

So, with debugging, I've found a solution : 

In src/Snapshot.php, in the function snapshotGlobals(), you try to serialize, and unserialize, this crash if it's a closure .

So, I've updated the function canBeSerialized(), with (on the begining of the function) : 

```php
if($variable instanceof \Closure)
            return false;
    
        if(is_array( $variable) || $variable instanceof \Iterator){
            foreach ( $variable as $item ) {
                if($item instanceof \Closure)
                    return false;
            }
        }
```

So, I check if $variable is a Closure, or if it's an array containing a closure .

In my case, the var $GLOBALS["functions"] contain two function, the phpunit autoloader, and the autoloader I write in my custom bootstrap file .

( In fact, the project I test doesn't respect the specs about spl_autoload_register, so I need to unregister this, and register a new function, respecting the specs )

I use phpunit 5.7.26

with

PHP 5.6.24 (cli) (built: Jul 20 2016 21:19:29)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

On windows

**Comment by harikt** [comment]
If serialization is really required, may be use https://github.com/jeremeamia/super_closure ?

**Comment by pretzlaw** [comment]
As closures are some kind of bad usage I suggest adding a try catch block in 
`\SebastianBergmann\GlobalState\Snapshot::snapshotSuperGlobalArray`
and add the `$key` in the error output.
This would help a lot to know which thing is crashing instead of a message like this:

> Exception: Serialization of 'Closure' is not allowed

Something somewhere failed somehow. Even `phpunit -vvv` does not help.

**Comment by pretzlaw** [comment]
Closures should be avoided anyway. Maybe @sebastianbergmann can change this in `\SebastianBergmann\GlobalState\Snapshot::snapshotGlobals` to point out what part contains a closure. Currently the exceptions says:

> Exception: Serialization of 'Closure' is not allowed

Better would be:

> Exception: Serialization of 'Closure' is not allowed (found in $GLOBALS[foo][bar][10][000000006fb4ea64000000004331bec6][function])


Which can be done like this for example:

```
/**
     * Creates a snapshot of all global and super-global variables.
     */
    private function snapshotGlobals()
    {
        $superGlobalArrays = $this->superGlobalArrays();

        foreach ($superGlobalArrays as $superGlobalArray) {
            $this->snapshotSuperGlobalArray($superGlobalArray);
        }

        foreach (\array_keys($GLOBALS) as $key) {
            if ($key != 'GLOBALS' &&
                !\in_array($key, $superGlobalArrays) &&
                $this->canBeSerialized($GLOBALS[$key]) &&
                !$this->blacklist->isGlobalVariableBlacklisted($key)) {
 // try catch
	            try {
	                $this->globalVariables[$key] = \unserialize(\serialize($GLOBALS[$key]));
	            } catch (\Exception $e) {
// show path to first closure
            		$this->throwClosureException($GLOBALS[$key], '$GLOBALS[' . $key . ']');
	            }
            }
        }
    }

	private function throwClosureException( $unserializable, $path ) {
		if ( \is_array($unserializable) || $unserializable instanceof \Iterator) { // or is_iterable for PHP >=7.1
			foreach ($unserializable as $key => $value) {
				$this->throwClosureException( $value, $path . '[' . $key . ']' );
			}
		}

// recursed already, but try one more time in case we couldn't hit a public field
		try {
			\serialize($unserializable);
		} catch (\Exception $e) {
			throw new \Exception( 'Closure within ' . $path . ' can not be serialized' );
		}
	}
```

**Comment by Mte90** [comment]
I am getting this issues too...

**Comment by thib3113** [comment]
@Mte90 : in my case, I've updated the file manually with my code above

**Comment by Mte90** [comment]
```    private function canBeSerialized($variable): bool
    {
		if($variable instanceof \Closure)
            return false;

        if(is_array( $variable) || $variable instanceof \Iterator){
            foreach ( $variable as $item ) {
                if($item instanceof \Closure)
                    return false;
            }
        }
        if (!\is_object($variable)) {
            return !\is_resource($variable);
        }

        if ($variable instanceof \stdClass) {
            return true;
        }

        $class = new ReflectionClass($variable);

        do {
            if ($class->isInternal()) {
                return $variable instanceof Serializable;
            }
        } while ($class = $class->getParentClass());

        return true;
    }```
Do you mean in that way? I am still getting the error

**Comment by thib3113** [comment]
So, It's seems is not the same error :/ . Or maybe a closure in an array, in an array ? maybe need you to do a recursive function :) .

**Comment by Mte90** [comment]
You are right, with the other code (https://github.com/sebastianbergmann/global-state/issues/13#issuecomment-385465056) I saw that is a function with another anonymous function inside
