### ISSUE TITLE
Make sure that static attributes of all user-defined classes are reset

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/global-state#4]
Moved here from https://github.com/sebastianbergmann/phpunit/issues/1372.

**Comment by JoostHouben** [comment]
This issue should be reopened: see the comment on the commit that closed this issue, and the third comment on sebastianbergmann/phpunit#1372.

**Comment by sebastianbergmann** [comment]
Please open a new ticket with a reproducing example.
