### ISSUE TITLE
Attempted to serialize unserializable builtin class PDO

### ISSUE THREAD

**Issue by elazar** [sebastianbergmann/global-state#8]
This error occurs when a global variable is present that has an array containing a `PDO` instance assigned to it.

The issue appears to stem from lack of support for this particular scenario in [`Snapshot->canBeSerialized()`](https://github.com/sebastianbergmann/global-state/blob/80e75e39bd6895a2240f5f959a5fec2df501d339/src/Snapshot.php#L403-L422).

I encountered this behavior while running PHPUnit tests in an environment where PHP configured to use xhprof, which unfortunately [uses a global for its configuration](https://github.com/staabm/xhprof.io/blob/76c295dec625fe152ff993cb02fd7800f38e6bf1/inc/prepend.php#L12) and [contains a `PDO` instance in said configuration](https://github.com/staabm/xhprof.io/blob/76c295dec625fe152ff993cb02fd7800f38e6bf1/xhprof/includes/config.inc.sample.php#L5).

It's possible this issue may be resolved with #3. Until it is, it appears there's no way to run PHPUnit with `@backupGlobals` and xhprof enabled without modifying xhprof core files.

**Comment by malkusch** [comment]
Thank you for creating this issue. #3 looks indeed like a rescue. I just wanted to bring up the same issue in the context of `@backupStaticAttributes`. `Snapshot::canBeSerialized()` does look only at the directly passed attribute (from `snapshotStaticAttributes()`). Unfortunately if any deeper property of that passed object does have an unserializable object it bails out.

**Comment by sebastianbergmann** [comment]
Closes in favour of #12.
